config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "tops#show"
  get "sessions/new"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: %i[index show] do
    resource :following, only: %i[show]
    resource :followers, only: %i[show]
  end
  resources :books, :reports, :comments
  resources :follows, only: %i[create destroy]
  resource :tops, only: %i[show]
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :content, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy]

  def create
    @comment = current_user.comments.new(comment_params)
    redirect_to @comment.commentable, notice: t("messages.created") if @comment.save
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    if @comment.update(comment_params)
      redirect_to @comment.commentable, notice: t("messages.updated")
    end
  end

  def destroy
    comment_parent = @comment.commentable
    @comment.destroy
    redirect_to comment_parent, notice: t("messages.destroyed")
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :commentable_id, :commentable_type)
    end

    def identity_verification
      if @comment.user != current_user
        flash[:notice] = t("messages.userself_only")
        redirect_to @comment.commentable
      end
    end
end

app/views/comments/_edit_link.html.erb
<% if comment.user == current_user %>
  <td>
    <%= link_to t('helpers.select.Edit'), edit_comment_path(comment) %>
  </td>
  <td>
    <%= link_to t('helpers.select.Destroy'), comment_path(comment), 
        method: :delete, data: { confirm: t('messages.sure?') } %>
  </td>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: comment, local: true do |form| %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%= form.hidden_field :commentable_type, value: comment.commentable_type %>
  <%= form.hidden_field :commentable_id, value: comment.commentable_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% unless comments.empty? %>
  <table>
    <thead>
      <tr>
        <th><%= Comment.human_attribute_name(:content) %></th>
        <th><%= User.human_attribute_name(:username) %></th>
      </tr>
    </thead>

    <tbody>
      <% comments.each do |comment| %>
        <% if comment.content %>
          <tr>
            <td><%= comment.content %></td>
            <td><%= link_to comment.user.username, comment.user %></td>
            <%= render 'comments/edit_link', comment: comment %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/comments/edit.html.erb
<h1><%= t('helpers.column.Edit_item', item: "コメント") %></h1><br>
<%= render 'form', comment: @comment %>