config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "tops#show"
  get "sessions/new"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: %i[index show] do
    resource :following, only: %i[show]
    resource :followers, only: %i[show]
  end
  resources :books, :reports, :comments
  resources :follows, only: %i[create destroy]
  resource :tops, only: %i[show]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :followed
  has_many :followers, through: :passive_follows, source: :follower

  has_one_attached :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  validates :username, presence: true
  validate :file_validation, if: :image_attached?

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    user ||= User.create(
      username: User.dummy_name(auth),
      uid: auth.uid,
      provider: auth.provider,
      email: User.dummy_email(auth),
      password: Devise.friendly_token[0, 20]
    )
    user.save
    user
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_follows.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  private
    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end

    def self.dummy_name(auth)
      "name:#{auth.uid}-#{auth.provider}"
    end

    def image_attached?
      image.attached?
    end

    def file_validation
      if image.blob.byte_size > 1_000_000
        file_raise_error
      elsif !image.blob.content_type.starts_with?("image/")
        file_raise_error
      end
    end

    def file_raise_error
      errors.add(:image)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    provider = provider.to_s

    @user = User.find_for_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = t("messages.github_login")
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource_or_scope)
    flash[:notice] = t("messages.sign_up_successfully")
    root_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource_or_scope)
    flash[:notice] = t("messages.login_successfully")
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    flash[:notice] = t("messages.logout_successfully")
    root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end

  def show
    if @user
      posts = Book.where(user: @user) + Report.where(user: @user)
      @posts = posts.sort_by { |post| post[:updated_at] }.reverse
      render "users/mypage" if @user == current_user
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_follow.html.erb
<% if current_user.following?(user) %>
  <%= form_for(current_user.active_follows.find_by(followed_id: user.id), 
      method: :delete) do |f| %>
    <%= f.submit "Unfollow", class: "btn" %>
  <% end %>
<% elsif user != current_user %>
  <%= form_for(current_user.active_follows.build) do |f| %>
    <%= hidden_field_tag :followed_id, user.id %></div>
    <%= f.submit "Follow", class: "btn" %>
  <% end %>
<% end %>

app/views/users/shared/_header.html.erb
<h1>
  <%= t('helpers.select.account_info', username: user.username ) %>
</h1><br>
<p id="notice">
  <%= notice %>
</p>
<%= link_to t('helpers.select.back_to', page: "トップページ"), root_path %><br>
<%= link_to t('helpers.column.following_count', num: user.following.count), user_following_path(user.id) %> |
<%= link_to t('helpers.column.followers_count', num: user.followers.count), user_followers_path(user.id) %>
<%= render 'users/shared/follow', user: user %>
<hr>

app/views/users/shared/_item_table.html.erb
<h2>
  <%= t('helpers.column.list_of_posts') %>
</h2>
<% if posts.empty? %>
  <h3>
    <%= t('messages.no_posts') %>
  </h3>
<% else %>
  <table>
    <thead>
      <tr>
        <th>
          <%= t('helpers.column.category') %>
        </th>
        <th>
          <%= t('helpers.column.Title') %>
        </th>
        <th>
          <%= Book.human_attribute_name(:updated_at) %>
        </th>
        <th>
          <%= User.human_attribute_name(:username) %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% posts.each do |post| %>
        <tr>
          <td>
            <%= post.class %>
          </td>
          <td>
            <%= link_to post.title, post %>
          </td>
          <td>
            <%= l post.updated_at, format: :short %>
          </td>
          <td>
            <%= link_to post.user.username, post.user %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('helpers.select.login'), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('helpers.select.signup'), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

app/views/users/shared/_table.html.erb
<% if users.empty? %>
  <h3>
    <%= t('messages.no_user') %>
  </h3>
<% else %>
  <table>
    <thead>
      <tr>
        <th>
          <%= User.human_attribute_name(:image) %>
        </th>
        <th>
          <%= User.human_attribute_name(:username) %>
        </th>
        <th>
          <%= User.human_attribute_name(:introduction) %>
        </th>
      </tr>
    </thead>

    <tbody>
      <% users.each do |user| %>
        <tr>
          <td>
            <%= image_tag user.image, :size =>'50x50' if user.image.attached? %>
          </td>
          <td>
            <%= link_to user.username, user %>
          </td>
          <td>
            <%= user.introduction %>
          </td>
          <td>
            <%= render 'users/shared/follow', user: user %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>