config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "tops#show"
  get "sessions/new"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: %i[index show] do
    resource :following, only: %i[show]
    resource :followers, only: %i[show]
  end
  resources :books, :reports, :comments
  resources :follows, only: %i[create destroy]
  resource :tops, only: %i[show]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :followed
  has_many :followers, through: :passive_follows, source: :follower

  has_one_attached :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  validates :username, presence: true
  validate :file_validation, if: :image_attached?

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    user ||= User.create(
      username: User.dummy_name(auth),
      uid: auth.uid,
      provider: auth.provider,
      email: User.dummy_email(auth),
      password: Devise.friendly_token[0, 20]
    )
    user.save
    user
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_follows.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  private
    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end

    def self.dummy_name(auth)
      "name:#{auth.uid}-#{auth.provider}"
    end

    def image_attached?
      image.attached?
    end

    def file_validation
      if image.blob.byte_size > 1_000_000
        file_raise_error
      elsif !image.blob.content_type.starts_with?("image/")
        file_raise_error
      end
    end

    def file_raise_error
      errors.add(:image)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    provider = provider.to_s

    @user = User.find_for_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = t("messages.github_login")
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource_or_scope)
    flash[:notice] = t("messages.sign_up_successfully")
    root_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource_or_scope)
    flash[:notice] = t("messages.login_successfully")
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    flash[:notice] = t("messages.logout_successfully")
    root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end

  def show
    if @user
      posts = Book.where(user: @user) + Report.where(user: @user)
      @posts = posts.sort_by { |post| post[:updated_at] }.reverse
      render "users/mypage" if @user == current_user
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/views/users/index.html.erb
<h1>
  <%= t('helpers.select.account_index', terms: "") %>
</h1><br>
<%= link_to t('helpers.select.back_to', page: "トップページ"), root_path %>
<hr>
<%= render 'users/shared/table', users: @users %>

app/views/users/mypage.html.erb
<%= render 'users/shared/header', user: @user %>
<p>
  <strong>
    <%= User.human_attribute_name(:username) %>:
  </strong>
  <%= @user.username %>
</p>

<p>
  <strong>
    <%= User.human_attribute_name(:email) %>:
  </strong>
  <%= @user.email %>
</p>

<p>
  <strong>
    <%= User.human_attribute_name(:postcode) %>:
  </strong>
  <%= @user.postcode %>
</p>

<p>
  <strong>
    <%= User.human_attribute_name(:address) %>:
  </strong>
  <%= @user.address %>
</p>

<p>
  <strong>
    <%= User.human_attribute_name(:introduction) %>：
  </strong>
  <%= @user.introduction %>
</p>

<hr>
<h2>
  <%= t('helpers.column.list_of_posts') %>
</h2>
<% if @posts.empty? %>
  <h3>
    <%= t('messages.no_posts') %>
  </h3>
<% else %>
  <table>
    <thead>
      <tr>
        <th>
          <%= t('helpers.column.category') %>
        </th>
        <th>
          <%= t('helpers.column.Title') %>
        </th>
        <th>
          <%= Book.human_attribute_name(:updated_at) %>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <%= post.class %>
          </td>
          <td>
            <%= link_to post.title, post %>
          </td>
          <td>
            <%= l post.updated_at, format: :short %>
          </td>
          <td>
            <% if post.class == Book %>
              <%= link_to t('helpers.select.Edit'), edit_book_path(post.id) %>
            <% else %>
              <%= link_to t('helpers.select.Edit'), edit_report_path(post.id) %>
            <% end %>
          </td>
          <td>
            <%= link_to t('helpers.select.Destroy'), post, method: :delete, data: { confirm: t('messages.sure?') } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<hr>
<%= link_to t('helpers.select.add_item', item: "本の感想"), new_book_path %>
<%= link_to t('helpers.select.add_item', item: "レポート"), new_report_path %>

app/views/users/show.html.erb
<% if @user %>
  <%= render 'users/shared/header', user: @user %>
  <p>
    <strong>
      <%= User.human_attribute_name(:username) %>:
    </strong>
    <%= @user.username %>
  </p>

  <p>
    <strong>
      <%= User.human_attribute_name(:image) %>:
    </strong>
    <%= image_tag @user.image, size: '150x150' if @user.image.attached? %>
  </p>

  <p>
    <strong>
      <%= User.human_attribute_name(:introduction) %>：
    </strong>
    <%= @user.introduction %>
  </p>

  <hr>
  <%= render 'users/shared/item_table', posts: @posts %><br>
<% else %>
  <%= link_to t('helpers.select.back_to', page: "トップページ"), root_path %><br>
  <h3>
    <%= t('messages.no_user') %>
  </h3>
<% end %>

app/views/users/top.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('helpers.select.app_title') %></h1><br>
<% if user_signed_in? %>
  <%= link_to t('helpers.select.account_info', username:""), current_user %> |
  <%= link_to t('helpers.select.account_index', terms: ""), users_path %> |
  <%= link_to t('helpers.select.logout'), destroy_user_session_path, method: :delete %>
  <hr>
  <%= render 'users/shared/item_table', posts: @posts %>
  <hr>
  <%= link_to t('helpers.select.add_item', item: "本の感想"), new_book_path %>
<% else %>
  <%= link_to t('helpers.select.signup'), new_user_registration_path %>
  <%= link_to t('helpers.select.login'), new_user_session_path %>
<% end %>  
<br>